### ISSUE TITLE
Network IP address error when approving the nodes

### ISSUE THREAD

**Issue by promiseowolabi** [NetApp-StorageGRID/Kubernetes#1]
I get the below error when trying to approve the nodes. The nodes are discovers with a /32 IP, this is causing an issue, Storagegrid version is 11.2. Am I using the wrong pod networks?

422: Unprocessable Entity 
Validation failed. Please check the values you entered for errors.
Network IP address 192.168.194.234 must not be the subnet address.
Network IP address 192.168.194.234 must not be the subnet broadcast address.

![image](https://user-images.githubusercontent.com/8224019/94908488-a33b1e00-0499-11eb-8d12-8e14ec88d2a2.png)

**Comment by mmears** [comment]
Hi Promise,

This is a known issue -- /32 CIDRs don’t work with StorageGRID until 11.4.  I’d try with 11.4.  If that’s not feasible, you’ll need to experiment to try to get k8s to allocate larger subnets.

--Morgan

**Comment by promiseowolabi** [comment]
Thanks a lot, I will get 11.4 👍🏾
